"""
Answer keys.

A key maps each question number to the SET of correct choices (a question
may have more than one correct answer). Choices are 0-based indexes, so
{3: {1}} means "question 3's answer is B".

Keys come from either:
  * a scanned answer-key sheet generated by this program (see grading.py,
    which reads it with the same scanner used for student sheets), or
  * a CSV file, parsed here. Accepted row formats (header row optional):
        1,B
        2,"A,C"     (several correct answers)
        3,A;C       (";" "|" "/" or spaces also work)
        4,AC
        5,B,D       (extra cells are extra correct answers)
"""

import csv
import io
import re
from dataclasses import dataclass

from .sheet_layout import CHOICE_LETTERS, MAX_QUESTIONS


class AnswerKeyError(ValueError):
    """Raised when an answer key is missing, unreadable or inconsistent."""


@dataclass
class AnswerKey:
    answers: dict[int, frozenset[int]]  # question number -> correct choice indexes
    num_choices: int | None = None      # known when read from a key sheet
    exam_id: str | None = None          # known when read from a key sheet

    @property
    def num_questions(self) -> int:
        return max(self.answers) if self.answers else 0

    def letters(self, question: int) -> str:
        """Correct answer(s) for a question as letters, e.g. "AC"."""
        return "".join(CHOICE_LETTERS[c] for c in sorted(self.answers.get(question, ())))


def _parse_choices(cells: list[str]) -> frozenset[int]:
    """Turn answer cells like ["A;C"] or ["B", "D"] into choice indexes."""
    letters = re.sub(r"[\s,;|/]+", "", "".join(cells)).upper()
    if not letters:
        raise AnswerKeyError("blank answer")
    choices = set()
    for ch in letters:
        if ch not in CHOICE_LETTERS:
            raise AnswerKeyError(f"'{ch}' is not a valid answer letter (use A-{CHOICE_LETTERS[-1]})")
        choices.add(CHOICE_LETTERS.index(ch))
    return frozenset(choices)


def parse_key_csv(text: str) -> AnswerKey:
    """Parse a CSV answer key. Raises AnswerKeyError with a friendly message."""
    text = (text or "").lstrip("﻿").strip()
    if not text:
        raise AnswerKeyError("The answer key file is empty.")

    answers: dict[int, frozenset[int]] = {}
    for line_no, row in enumerate(csv.reader(io.StringIO(text)), start=1):
        cells = [c.strip() for c in row if c.strip()]
        if not cells:
            continue
        q_text = cells[0].rstrip(".):")
        if not q_text.isdigit():
            if line_no == 1:
                continue  # header row such as "Question,Answer"
            raise AnswerKeyError(f"Line {line_no}: '{cells[0]}' is not a question number.")
        q = int(q_text)
        if not 1 <= q <= MAX_QUESTIONS:
            raise AnswerKeyError(f"Line {line_no}: question {q} is out of range (1-{MAX_QUESTIONS}).")
        if q in answers:
            raise AnswerKeyError(f"Line {line_no}: question {q} appears more than once.")
        try:
            answers[q] = _parse_choices(cells[1:])
        except AnswerKeyError as exc:
            raise AnswerKeyError(f"Line {line_no} (question {q}): {exc}.") from None

    if not answers:
        raise AnswerKeyError("No answers were found in the answer key file.")
    missing = [q for q in range(1, max(answers) + 1) if q not in answers]
    if missing:
        raise AnswerKeyError(f"The answer key is missing question(s): {', '.join(map(str, missing[:10]))}.")
    return AnswerKey(answers=answers)


def parse_versioned_key_csv(text: str) -> dict[int, AnswerKey] | None:
    """Parse a multi-version key: a header row "Question, Version 1, Version 2, ..."
    then one row per question with each version's answer in its column.

    Returns {version: AnswerKey}, or None if the file has no version columns
    (it is then an ordinary single-version key).
    """
    text = (text or "").lstrip("\ufeff").strip()
    rows = [r for r in csv.reader(io.StringIO(text)) if any(c.strip() for c in r)]
    if not rows:
        return None
    header = [c.strip().lower() for c in rows[0]]
    version_cols = {}
    for i, h in enumerate(header):
        m = re.fullmatch(r"(?:version|ver|v)\s*(\d)", h)
        if m:
            version_cols[int(m.group(1))] = i
    if not version_cols:
        return None
    if sorted(version_cols) != list(range(1, len(version_cols) + 1)) or len(version_cols) > 4:
        raise AnswerKeyError("Version columns should be Version 1, Version 2, ... (up to 4).")

    keys = {}
    for version, col in version_cols.items():
        lines = []
        for row in rows[1:]:
            q = row[0].strip() if row else ""
            a = row[col].strip() if col < len(row) else ""
            lines.append(f'{q},"{a}"')
        try:
            keys[version] = parse_key_csv("\n".join(lines))
        except AnswerKeyError as exc:
            raise AnswerKeyError(f"Version {version}: {exc}") from None
    counts = {k.num_questions for k in keys.values()}
    if len(counts) > 1:
        raise AnswerKeyError("Every version must have the same number of questions.")
    return keys
